In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('datasets/census.csv')
# And exclude state level summarizations, which have sum level value of 40
df = df[df['SUMLEV']==50]

## groupby

groupby的结果是在迭代器里面，可以for循环取出来

In [4]:
for group, frame in df.groupby('STNAME'):
    # groupby() returns a tuple, where the first value is the
    # value of the key we were trying to group by, in this case 
    # a specific state name, and the second one is
    # projected dataframe that was found for that group
    
    avg = np.average(frame['CENSUS2010POP'])
    print('Counties in state ' + group + 
          ' have an average population of ' + str(avg))

Counties in state Alabama have an average population of 71339.34328358209
Counties in state Alaska have an average population of 24490.724137931036
Counties in state Arizona have an average population of 426134.4666666667
Counties in state Arkansas have an average population of 38878.90666666667
Counties in state California have an average population of 642309.5862068966
Counties in state Colorado have an average population of 78581.1875
Counties in state Connecticut have an average population of 446762.125
Counties in state Delaware have an average population of 299311.3333333333
Counties in state District of Columbia have an average population of 601723.0
Counties in state Florida have an average population of 280616.5671641791
Counties in state Georgia have an average population of 60928.63522012578
Counties in state Hawaii have an average population of 272060.2
Counties in state Idaho have an average population of 35626.86363636364
Counties in state Illinois have an average population of 125790.50980392157
Counties in state Indiana have an average population of 70476.10869565218
Counties in state Iowa have an average population of 30771.262626262625
Counties in state Kansas have an average population of 27172.55238095238
Counties in state Kentucky have an average population of 36161.39166666667
Counties in state Louisiana have an average population of 70833.9375
Counties in state Maine have an average population of 83022.5625
Counties in state Maryland have an average population of 240564.66666666666
Counties in state Massachusetts have an average population of 467687.78571428574
Counties in state Michigan have an average population of 119080.0
Counties in state Minnesota have an average population of 60964.65517241379
Counties in state Mississippi have an average population of 36186.54878048781
Counties in state Missouri have an average population of 52077.62608695652
Counties in state Montana have an average population of 17668.125
Counties in state Nebraska have an average population of 19638.075268817203
Counties in state Nevada have an average population of 158855.9411764706
Counties in state New Hampshire have an average population of 131647.0
Counties in state New Jersey have an average population of 418661.61904761905
Counties in state New Mexico have an average population of 62399.36363636364
Counties in state New York have an average population of 312550.03225806454
Counties in state North Carolina have an average population of 95354.83
Counties in state North Dakota have an average population of 12690.396226415094
Counties in state Ohio have an average population of 131096.63636363635
Counties in state Oklahoma have an average population of 48718.844155844155
Counties in state Oregon have an average population of 106418.72222222222
Counties in state Pennsylvania have an average population of 189587.74626865672
Counties in state Rhode Island have an average population of 210513.4
Counties in state South Carolina have an average population of 100551.39130434782
Counties in state South Dakota have an average population of 12336.060606060606
Counties in state Tennessee have an average population of 66801.1052631579
Counties in state Texas have an average population of 98998.27165354331
Counties in state Utah have an average population of 95306.37931034483
Counties in state Vermont have an average population of 44695.78571428572
Counties in state Virginia have an average population of 60111.29323308271
Counties in state Washington have an average population of 172424.10256410256
Counties in state West Virginia have an average population of 33690.8
Counties in state Wisconsin have an average population of 78985.91666666667
Counties in state Wyoming have an average population of 24505.478260869564

groupby可以传入函数进行分组

In [5]:
df = df.set_index('STNAME')

In [6]:
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
STNAME,,,,,,,,,,,,,,,,,,,,,
Alabama,50,3,6,1,1,Autauga County,54571,54571,54660,55253,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
Alabama,50,3,6,1,3,Baldwin County,182265,182265,183193,186659,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
Alabama,50,3,6,1,5,Barbour County,27457,27457,27341,27226,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
Alabama,50,3,6,1,7,Bibb County,22915,22919,22861,22733,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
Alabama,50,3,6,1,9,Blount County,57322,57322,57373,57711,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411

In [9]:
def set_batch_number(item):
    if item[0] < 'M':
        return 0
    if item[0] < 'Q':
        return 1
    return 2

for group, frame in df.groupby(set_batch_number):
    print(f'{group}: {frame.shape}')

0: (1177, 99)
1: (1134, 99)
2: (831, 99)

## agg

In [11]:
df=pd.read_csv("datasets/listings.csv")
df.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,12147973,https://www.airbnb.com/rooms/12147973,20160906204935,2016-09-07,Sunny Bungalow in the City,"Cozy, sunny, family home. Master bedroom high...",The house has an open and cozy feel at the sam...,"Cozy, sunny, family home. Master bedroom high...",none,"Roslindale is quiet, convenient and friendly. ...",...,NaN,f,NaN,NaN,f,moderate,f,f,1,NaN
1,3075044,https://www.airbnb.com/rooms/3075044,20160906204935,2016-09-07,Charming room in pet friendly apt,Charming and quiet room in a second floor 1910...,Small but cozy and quite room with a full size...,Charming and quiet room in a second floor 1910...,none,"The room is in Roslindale, a diverse and prima...",...,9.0,f,NaN,NaN,t,moderate,f,f,1,1.30
2,6976,https://www.airbnb.com/rooms/6976,20160906204935,2016-09-07,Mexican Folk Art Haven in Boston,"Come stay with a friendly, middle-aged guy in ...","Come stay with a friendly, middle-aged guy in ...","Come stay with a friendly, middle-aged guy in ...",none,The LOCATION: Roslindale is a safe and diverse...,...,10.0,f,NaN,NaN,f,moderate,t,f,1,0.47
3,1436513,https://www.airbnb.com/rooms/1436513,20160906204935,2016-09-07,Spacious Sunny Bedroom Suite in Historic Home,Come experience the comforts of home away from...,Most places you find in Boston are small howev...,Come experience the comforts of home away from...,none,Roslindale is a lovely little neighborhood loc...,...,10.0,f,NaN,NaN,f,moderate,f,f,1,1.00
4,7651065,https://www.airbnb.com/rooms/7651065,20160906204935,2016-09-07,Come Home to Boston,"My comfy, clean and relaxing home is one block...","Clean, attractive, private room, one block fro...","My comfy, clean and relaxing home is one block...",none,"I love the proximity to downtown, the neighbor...",...,10.0,f,NaN,NaN,f,flexible,f,f,1,2.25

In [12]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       'notes', 'transit', 'access', 'interaction', 'house_rules',
       'thumbnail_url', 'medium_url', 'picture_url', 'xl_picture_url',
       'host_id', 'host_url', 'host_name', 'host_since', 'host_location',
       'host_about', 'host_response_time', 'host_response_rate',
       'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url',
       'host_picture_url', 'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'street',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
       'is_location_exact', 'property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'square_feet',
       'price', 'weekly_price', 'monthly_price', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'first_review', 'last_review', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'requires_license',
       'license', 'jurisdiction_names', 'instant_bookable',
       'cancellation_policy', 'require_guest_profile_picture',
       'require_guest_phone_verification', 'calculated_host_listings_count',
       'reviews_per_month'],
      dtype='object')

In [13]:
df.groupby("cancellation_policy").agg({"review_scores_value":(np.nanmean,np.nanstd),
                                      "reviews_per_month":np.nanmean})

                    review_scores_value           reviews_per_month
                                nanmean    nanstd           nanmean
cancellation_policy
flexible                       9.237421  1.096271          1.829210
moderate                       9.307398  0.859859          2.391922
strict                         9.081441  1.040531          1.873467
super_strict_30                8.537313  0.840785          0.340143

## transformation

transform 返回的数据大小与原本data的size相同，这使得数据的合并非常容易

In [18]:
cols=['cancellation_policy','review_scores_value']
transform_df = df[cols].groupby(cols[0]).transform(np.nanmean)
transform_df.head()

   review_scores_value
0             9.307398
1             9.307398
2             9.307398
3             9.307398
4             9.237421

In [ ]:
transform_df.rename({'review_scores_value':'mean_review_scores'}, axis='columns', inplace=True)
df=df.merge(transform_df, left_index=True, right_index=True)
df.head()

## filtering

In [19]:
df.groupby('cancellation_policy').filter(lambda x: np.nanmean(x['review_scores_value'])>9.2)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,12147973,https://www.airbnb.com/rooms/12147973,20160906204935,2016-09-07,Sunny Bungalow in the City,"Cozy, sunny, family home. Master bedroom high...",The house has an open and cozy feel at the sam...,"Cozy, sunny, family home. Master bedroom high...",none,"Roslindale is quiet, convenient and friendly. ...",...,NaN,f,NaN,NaN,f,moderate,f,f,1,NaN
1,3075044,https://www.airbnb.com/rooms/3075044,20160906204935,2016-09-07,Charming room in pet friendly apt,Charming and quiet room in a second floor 1910...,Small but cozy and quite room with a full size...,Charming and quiet room in a second floor 1910...,none,"The room is in Roslindale, a diverse and prima...",...,9.0,f,NaN,NaN,t,moderate,f,f,1,1.30
2,6976,https://www.airbnb.com/rooms/6976,20160906204935,2016-09-07,Mexican Folk Art Haven in Boston,"Come stay with a friendly, middle-aged guy in ...","Come stay with a friendly, middle-aged guy in ...","Come stay with a friendly, middle-aged guy in ...",none,The LOCATION: Roslindale is a safe and diverse...,...,10.0,f,NaN,NaN,f,moderate,t,f,1,0.47
3,1436513,https://www.airbnb.com/rooms/1436513,20160906204935,2016-09-07,Spacious Sunny Bedroom Suite in Historic Home,Come experience the comforts of home away from...,Most places you find in Boston are small howev...,Come experience the comforts of home away from...,none,Roslindale is a lovely little neighborhood loc...,...,10.0,f,NaN,NaN,f,moderate,f,f,1,1.00
4,7651065,https://www.airbnb.com/rooms/7651065,20160906204935,2016-09-07,Come Home to Boston,"My comfy, clean and relaxing home is one block...","Clean, attractive, private room, one block fro...","My comfy, clean and relaxing home is one block...",none,"I love the proximity to downtown, the neighbor...",...,10.0,f,NaN,NaN,f,flexible,f,f,1,2.25
5,12386020,https://www.airbnb.com/rooms/12386020,20160906204935,2016-09-07,Private Bedroom + Great Coffee,Super comfy bedroom plus your own bathroom in ...,Our sunny condo is located on the second and t...,Super comfy bedroom plus your own bathroom in ...,none,We love our corner of Roslindale! For quiet wa...,...,10.0,f,NaN,NaN,f,flexible,f,f,1,1.70
7,2843445,https://www.airbnb.com/rooms/2843445,20160906204935,2016-09-07,"""Tranquility"" on ""Top of the Hill""","We can accommodate guests who are gluten-free,...",We provide a bedroom and full shared bath. Ra...,"We can accommodate guests who are gluten-free,...",none,Our neighborhood is residential with friendly ...,...,10.0,f,NaN,NaN,f,moderate,t,t,2,2.38
8,753446,https://www.airbnb.com/rooms/753446,20160906204935,2016-09-07,6 miles away from downtown Boston!,Nice and cozy apartment about 6 miles away to ...,Nice and cozy apartment about 6 miles away to ...,Nice and cozy apartment about 6 miles away to ...,none,Roslindale is a primarily residential neighbor...,...,10.0,f,NaN,NaN,f,moderate,f,f,1,5.36
10,12023024,https://www.airbnb.com/rooms/12023024,20160906204935,2016-09-07,Cozy room in a well located house,The room is in a single family house located i...,NaN,The room is in a single family house located i...,none,NaN,...,10.0,f,NaN,NaN,f,flexible,f,f,1,0.36
11,1668313,https://www.airbnb.com/rooms/1668313,20160906204935,2016-09-07,Room in Rozzie-Twin Bed-Full Bath,Quiet second floor bedroom sleeps one in comfo...,NaN,Quiet second floor bedroom sleeps one in comfo...,none,Our neighborhood is quiet and relaxed. There i...,...,9.0,f,NaN,NaN,f,flexible,f,f,2,0.48
12,2684840,https://www.airbnb.com/rooms/2684840,20160906204935,2016-09-07,"Updated, spacious living in Rozzie","Clean, sunny 2 bedroom in amazing Roslindale V...",NaN,"Clean, sunny 2 bedroom in amazing Roslindale V...",none,NaN,...,10.0,f,NaN,NaN,t,flexible,f,f,2,0.64
13,13547301,https://www.airbnb.com/rooms/13547301,20160906204935,2016-09-07,2 Bedroom Apartment in Boston,My place is close to Public Transportation. Th...,NaN,My place is close to Public Transportation. Th...,none,NaN,...,10.0,f,NaN,NaN,f,moderate,f,f,1,4.93
14,5434353,https://www.airbnb.com/rooms/5434353,20160906204935,2016-09-07,Quiet Beauty in Boston,Enjoy the full space of our home as you explor...,Large living and dining area. Sprawling space....,Enjoy the full space of our home as you explor...,none,"Quiet Roslindale, close to the trendy Jamaica ...",...,9.0,f,NaN,NaN,f,moderate,f,f,1,0.56
16,3420384,https://www.airbnb.com/rooms/3420384,20160906204935,2016-09-07,"Convient, Safe and Comfortable",Located along public transportation with plent...,"Extra large studio with wifi, cable, original ...",Located along public transportation with plent...,none,"Village 1 mile with banks, grocery store, spec...",...,10.0,f,NaN,NaN,f,flexible,f,f,1,1.00
17,13512930,https://www.airbnb.com/rooms/13512930,20160906204935,2016-09-07,Roslindale Beauty next to Arboretum,"Clean, sunny 1 bedroom in amazing Roslindale V...",NaN,"Clean, sunny 1 bedroom in amazing Roslindale V...",none,NaN,...,10.0,f,NaN,NaN,t,flexible,f,f,2,0.37
20,2583074,https://www.airbnb.com/rooms/2583074,20160906204935,2016-09-07,Cozy room in a charming villa.,"My home is a villa in one of the friendliest, ...",The room is cozy and private. The house is les...,"My home is a villa in one of the friendliest, ...",none,"This a nice multicultural, family neighborhood...",...,10.0,f,NaN,NaN,f,flexible,f,f,3,1.24
21,13251243,https://www.airbnb.com/rooms/13251243,20160906204935,2016-09-07,Arborside Guest Cottage,Lovely sun-filled private guest cottage set on...,"Today the cottage could be called a ""tiny hous...",Lovely sun-filled private guest cottage set on...,none,This Boston location is true gem - just a few ...,...,10.0,f,NaN,NaN,t,moderate,f,f,1,5.93
23,6400432,https://www.airbnb.com/rooms/6400432,20160906204935,2016-09-07,Spacious 3 bedroom cape cod style,Three bedroom in Boston's Roslindale neighborh...,This Cape Cod style home features two bedrooms...,Three bedroom in Boston's Roslindale neighborh...,none,NaN,...,10.0,f,NaN,NaN,f,flexible,f,f,1,1.58
24,5498472,https://www.airbnb.com/rooms/5498472,20160906204935,2016-09-07,"4BD/3.5BA, Perfect for families!","Our spacious, modern, immaculate town home is ...","Our 2,400+ square foot home is a hidden gem, t...","Our spacious, modern, immaculate town home is ...",none,"Roslindale is a quiet and family friendly, yet...",...,10.0,f,NaN,NaN,f,moderate,f,f,1,0.07
25,894539,https://www.airbnb.com/rooms/894539,20160906204935,2016-09-07,Private room in house,NaN,Large private room in a large house near the A...,Large private room in a large house near the A...,none,NaN,...,10.0,f,NaN,NaN,f,moderate,f,f,2,1.13
27,9218312,https://www.airbnb.com/rooms/9218312,20160906204935,2016-09-07,Sunny bedroom with private bathroom,"Located in the Peter's Hill neighborhood, rest...","Large sunny bedroom with double bed, love seat...","Located in the Peter's Hill neighborhood, rest...",none,We have lived in Roslindale since 1985 and hav...,...,10.0,f,NaN,NaN,f,moderate,f,f,1,4.02
28,321328,https://www.airbnb.com/rooms/321328,20160906204935,2016-09-07,Bright Room Near Roslindale Village,NaN,I have an attractive room available in Roslind...,I have an attractive room available in Roslind...,none,"Roslindale is a vibrant area of Boston, with r...",...,9.0,f,NaN,NaN,f,flexible,f,f,1,0.21
29,1810172,https://www.airbnb.com/rooms/1810172,20160906204935,2016-09-07,Room for 2 in Rozzie - Full Bath,This second floor bedroom sleeps two in a quee...,NaN,This second floor bedroom sleeps two in a quee...,none,Our neighborhood is quiet and relaxed. There i...,...,10.0,f,NaN,NaN,f,flexible,f,f,2,0.58
30,6513924,https://www.airbnb.com/rooms/6513924,20160906204935,2016-09-07,Private room in spacious condo!,Nice unit located within walking distance of c...,"Spacious, modern construction condo with plent...",Nice unit located within walking distance of c...,none,"Today's Roslindale is not the ""Rozzie"" of my y...",...,9.0,f,NaN,NaN,f,flexible,f,f,1,1.93
32,14690527,https://www.airbnb.com/rooms/14690527,20160906204935,2016-09-07,1 Bedroom Home Suite Home,"My place is good for couples, solo adventurers...",NaN,"My place is good for couples, solo adventurers...",none,NaN,...,NaN,f,NaN,NaN,t,flexible,f,f,1,NaN
34,1861070,https://www.airbnb.com/rooms/1861070,20160906204935,2016-09-07,Charming Gambrel on a sweet street,This home has been featured in several magazin...,"This beautiful house, filled with a lifetime o...",This home has been featured in several magazin...,none,Our home is located on the top of one of the t...,...,10.0,f,NaN,NaN,f,flexible,f,f,1,0.59
39,4085362,https://www.airbnb.com/rooms/4085362,20160906204935,2016-09-07,"""Room with a View"" from ""Top of the Hill""","We used to be called Sub""urban"" Vacationing. ...",We provide a bedroom and a full shared bath fo...,"We used to be called Sub""urban"" Vacationing. ...",none,Roslindale is one of the neighborhoods of Bost...,...,10.0,f,NaN,NaN,f,moderate,t,t,2,0.87
40,3755609,https://www.airbnb.com/rooms/3755609,20160906204935,2016-09-07,Lovely & Gracious Victorian room,Lovely & Gracious Victorian room offers the be...,"The room is lovely, sunny, decorated with auth...",Lovely & Gracious Victorian room offers the be...,none,Today's residents of Roslindale are attracted...,...,9.0,f,NaN,NaN,t,flexible,f,f,1,0.87
41,13768853,https://www.airbnb.com/rooms/13768853,20160906204935,2016-09-07,"Cozy, quiet room in Roslindale",If you're looking for a quiet place in a resid...,NaN,If you're looking for a quiet place in a resid...,none,NaN,...,10.0,f,NaN,NaN,f,flexible,f,f,1,5.77
42,1936861,https://www.airbnb.com/rooms/1936861,20160906204935,2016-09-07,Private Room in Rozzie,Private room with twin bed. Walking distance t...,"Simple, private space with a surprising amount...",Private room with twin bed. Walking distance t...,none,BE ADVISED: This is a super fun neighborhood i...,...,10.0,f,NaN,NaN,f,flexible,f,f,1,4.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3533,6373729,https://www.airbnb.com/rooms/6373729,20160906204935,2016-09-07,"American Vintage room, 2+ peeps ok",This is a classic American vintage house that ...,"Due to the age of this house, the heat system ...",This is a classic American vintage house that ...,none,"Nice, quiet and safe! Nothing happened to me ...",...,8.0,f,NaN,NaN,f,flexible,f,f,1,0.07
3534,8921130,https://www.airbnb.com/rooms/8921130,20160906204935,2016-09-07,"Beautiful, Modern, Furnished Apt!","This is a beautiful apt, equipped with new app...",NaN,"This is a beautiful apt, equipped with new app...",none,"Located right on the Brookline/Allston border,...",...,10.0,f,NaN,NaN,f,flexible,f,f,1,0.26
3535,10436811,https://www.airbnb.com/rooms/10436811,20160906204935,2016-09-07,"Bright, Clean & Great Location",Hello! I share the apparent with two good frie...,"My room is a private bedroom, with its own loc...",Hello! I share the apparent with two good frie...,none,The apartment is conveniently located in Allst...,...,NaN,f,NaN,NaN,t,flexible,f,f,1,NaN
3536,14026059,https://www.airbnb.com/rooms/14026059,20160906204935,2016-09-07,Large room near hospitals,My place is ideal for physicians and researche...,The bathroom would be shared with one other in...,My place is ideal for physicians and researche...,none,NaN,...,NaN,f,NaN,NaN,f,moderate,f,f,1,NaN
3539,4332035,https://www.airbnb.com/rooms/4332035,20160906204935,2016-09-07,Lux Brookline 1BR w/ gym & WiFi,This property is a newly renovated 3 story ele...,"Our beautiful apartments feature bay windows, ...",This property is a newly renovated 3 story ele...,none,"Living at this address, residents will enjoy t...",...,NaN,f,NaN,NaN,f,moderate,f,t,61,0.05
3540,9807292,https://www.airbnb.com/rooms/9807292,20160906204935,2016-09-07,Lux Brookline 2BR w/ gym & WiFi,This property is a newly renovated 3 story ele...,"Our beautiful apartments feature bay windows, ...",This property is a newly renovated 3 story ele...,none,"Living at this address, residents will enjoy t...",...,NaN,f,NaN,NaN,f,moderate,f,t,61,NaN
3543,14866400,https://www.airbnb.com/rooms/14866400,20160906204935,2016-09-07,"Cozy room, clean,luxury,next to T","My place is close to Sullivan T Station, Assem...",NaN,"My place is close to Sullivan T Station, Assem...",none,NaN,...,NaN,f,NaN,NaN,t,flexible,f,f,1,NaN
3545,14400847,https://www.airbnb.com/rooms/14400847,20160906204935,2016-09-07,"Quiet, charming and convenient",This quiet and appealing 3rd floor apartment i...,NaN,This quiet and appealing 3rd floor apartment i...,none,The apartment offers a peaceful place to sleep...,...,10.0,f,NaN,NaN,f,flexible,f,f,1,2.00
3548,14774426,https://www.airbnb.com/rooms/14774426,20160906204935,2016-09-07,Somerillve comfort room,我的房源靠近It's very close to the subway station. ...,NaN,我的房源靠近It's very close to the subway station. ...,none,NaN,...,10.0,f,NaN,NaN,f,moderate,f,f,1,1.00
3549,14487346,https://www.airbnb.com/rooms/14487346,20160906204935,2016-09-07,Comfort Private Room Close to T & BOSTON_#3C,"My place is good for couples, solo adventurers...",Modern and clean furnished private room for re...,"My place is good for couples, solo adventurers...",none,NaN,...,NaN,f,NaN,NaN,t,flexible,f,f,1,NaN
3550,14550228,https://www.airbnb.com/rooms/14550228,20160906204935,2016-09-07,Beautiful Room near MIT and Harvard,Private room in top floor of a high-rise. Clos...,Top floor of a high-rise right next to the Cha...,Private room in top floor of a high-rise. Clos...,none,"Diverse, friendly and beautiful neighborhood. ...",...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN
3551,14566657,https://www.airbnb.com/rooms/14566657,20160906204935,2016-09-07,Modern Loft North Point,Enjoy a great stay in East Cambridge ( North P...,NaN,Enjoy a great stay in East Cambridge ( North P...,none,NaN,...,6.0,f,NaN,NaN,t,moderate,f,f,2,1.00
3552,14773792,https://www.airbnb.com/rooms/14773792,20160906204935,2016-09-07,(N) Shared room near Harvard & MIT,This bed accommodates 2 and is a shared room w...,To ensure a smooth check in: 1. You MUST have ...,This bed accommodates 2 and is a shared room w...,none,NaN,...,NaN,f,NaN,NaN,t,flexible,f,f,3,NaN
3554,14533848,https://www.airbnb.com/rooms/14533848,20160906204935,2016-09-07,2 bedrooms available in 4 bed unit,"2 bedrooms, 1 with King bed and other with 2 s...",NaN,"2 bedrooms, 1 with King bed and other with 2 s...",none,NaN,...,10.0,f,NaN,NaN,f,flexible,f,f,1,2.00
3555,13015653,https://www.airbnb.com/rooms/13015653,20160906204935,2016-09-07,Big Room at Brookline Hill in Boston,The private room is big enough. My place is 5 ...,Your private room is big enough. And the livin...,The private room is big enough. My place is 5 ...,none,NaN,...,9.0,f,NaN,NaN,f,moderate,f,f,1,4.00
3557,14604429,https://www.airbnb.com/rooms/14604429,20160906204935,2016-09-07,Bedroom in to Allston/Brookline area for rent,"My place is close to BU, Brookline (Coolidge C...",NaN,"My place is close to BU, Brookline (Coolidge C...",none,NaN,...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN
3559,12915510,https://www.airbnb.com/rooms/12915510,20160906204935,2016-09-07,It's always more fun on the water,Our boat is used as a live-aboard and has more...,This 1965 Hatteras 50 foot motor-yacht was ful...,Our boat is used as a live-aboard and has more...,none,Charlestown Marina is newly renovated and has ...,...,10.0,f,NaN,NaN,f,moderate,f,f,1,1.28
3562,14881840,https://www.airbnb.com/rooms/14881840,20160906204935,2016-09-07,Modern hot spot studio,Modern cozy apartment with amazing location ri...,Super accessible to every outlet of the city,Modern cozy apartment with amazing location ri...,none,Super nice dining options within arms reach le...,...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN
3563,11452297,https://www.airbnb.com/rooms/11452297,20160906204935,2016-09-07,2bed/2bath apt. 3 miles from Boston,Newly renovated apartment available: - Updated...,Spacious first floor unit with private porch i...,Newly renovated apartment available: - Updated...,none,"Located on a quiet tree lined street, just a s...",...,NaN,f,NaN,NaN,f,moderate,f,f,1,NaN
3565,14335003,https://www.airbnb.com/rooms/14335003,20160906204935,2016-09-07,On Charles River near Harvard Square,"My place is a block from the Charles River, a ...",NaN,"My place is a block from the Charles River, a ...",none,NaN,...,10.0,f,NaN,NaN,t,flexible,f,f,1,1.00
3566,14871445,https://www.airbnb.com/rooms/14871445,20160906204935,2016-09-07,Private Room with half bathroom inside near Su...,"My place is good for couples, solo adventurers...",NaN,"My place is good for couples, solo adventurers...",none,NaN,...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN
3569,14426586,https://www.airbnb.com/rooms/14426586,20160906204935,2016-09-07,Condo for 4 close to Boston,1 private BR w/ full size bed and bath + a que...,NaN,1 private BR w/ full size bed and bath + a que...,none,NaN,...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN
3571,14592547,https://www.airbnb.com/rooms/14592547,20160906204935,2016-09-07,Private Room Boston/Brookline Great location,"My place is close to 4Acoffee, Starbucks, Harr...",Its a small room but cozy and comfortable. Per...,"My place is close to 4Acoffee, Starbucks, Harr...",none,We live in one of Boston's favorite neighborho...,...,10.0,f,NaN,NaN,f,flexible,f,f,1,2.00
3573,14504583,https://www.airbnb.com/rooms/14504583,20160906204935,2016-09-07,(J1) Private Room near Harvard/MIT,My place is close to My home is a warm and fri...,To ensure a smooth check in: 1. You MUST have ...,My place is close to My home is a warm and fri...,none,NaN,...,10.0,f,NaN,NaN,t,flexible,f,f,3,2.00
3574,14743129,https://www.airbnb.com/rooms/14743129,20160906204935,2016-09-07,Hancock Village rent out one room,"我的房源走路2 minutes有shopping mall,包括CVS,restuarant...",NaN,"我的房源走路2 minutes有shopping mall,包括CVS,restuarant...",none,"走路2 minutes有shopping mall,包括CVS,restuarant,ban...",...,8.0,f,NaN,NaN,f,moderate,f,f,2,1.00
3576,14689681,https://www.airbnb.com/rooms/14689681,20160906204935,2016-09-07,Beautiful loft style bedroom with large bathroom,You'd be living on the top floor of a four sto...,NaN,You'd be living on the top floor of a four sto...,none,NaN,...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN
3577,13750763,https://www.airbnb.com/rooms/13750763,20160906204935,2016-09-07,Comfortable Space in the Heart of Brookline,"Our place is close to Coolidge Corner, Allston...",This space consists of 2 Rooms and a private b...,"Our place is close to Coolidge Corner, Allston...",none,Brookline is known for being an excellent and ...,...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN
3579,14852179,https://www.airbnb.com/rooms/14852179,20160906204935,2016-09-07,Spacious Queen Bed Room Close to Boston Univer...,- Grocery: A full-size Star market is 2 minute...,NaN,- Grocery: A full-size Star market is 2 minute...,none,NaN,...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN
3582,14585486,https://www.airbnb.com/rooms/14585486,20160906204935,2016-09-07,Gorgeous funky apartment,Funky little apartment close to public transpo...,Modern and relaxed space with many facilities ...,Funky little apartment close to public transpo...,none,"Cambridge is a short walk into Boston, and set...",...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN
3584,14504422,https://www.airbnb.com/rooms/14504422,20160906204935,2016-09-07,(K1) Private Room near Harvard/MIT,My place is close to My home is a warm and fri...,To ensure a smooth check in: 1. You MUST have ...,My place is close to My home is a warm and fri...,none,NaN,...,NaN,f,NaN,NaN,t,flexible,f,f,3,NaN

## apply

In [21]:
df=pd.read_csv("datasets/listings.csv")
# And lets just include some of the columns we were interested in previously
df=df[['cancellation_policy','review_scores_value']]
df.head()

  cancellation_policy  review_scores_value
0            moderate                  NaN
1            moderate                  9.0
2            moderate                 10.0
3            moderate                 10.0
4            flexible                 10.0

In [ ]:
def calc_mean_review_scores(group):
    # group is a dataframe just of whatever we have grouped by, e.g. cancellation policy, so we can treat
    # this as the complete dataframe
    avg=np.nanmean(group["review_scores_value"])
    # now broadcast our formula and create a new column
    group["review_scores_mean"]=np.abs(avg-group["review_scores_value"])
    return group

# Now just apply this to the groups
df.groupby('cancellation_policy').apply(calc_mean_review_scores).head()

## Scales

我们可以将column数据类型更换为 category

构建category数据类型，并带上排序

In [24]:
df=pd.DataFrame(['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D'],
                index=['excellent', 'excellent', 'excellent', 'good', 'good', 'good', 
                       'ok', 'ok', 'ok', 'poor', 'poor'],
               columns=["Grades"])

In [25]:
my_categories=pd.CategoricalDtype(categories=['D', 'D+', 'C-', 'C', 'C+', 'B-', 'B', 'B+', 'A-', 'A', 'A+'], 
                           ordered=True)
# then we can just pass this to the astype() function
grades=df["Grades"].astype(my_categories)
grades.head()

excellent    A+
excellent     A
excellent    A-
good         B+
good          B
Name: Grades, dtype: category
Categories (11, object): [D < D+ < C- < C ... B+ < A- < A < A+]

可以看到，最终的类型，以及对应的排序

现在，我们就可以对value进行比较输出想要的rols

In [29]:
grades[grades > 'C']

excellent    A+
excellent     A
excellent    A-
good         B+
good          B
good         B-
ok           C+
Name: Grades, dtype: category
Categories (11, object): [D < D+ < C- < C ... B+ < A- < A < A+]

使用cut也可以将df数据分为制定数目的类别

In [31]:
import numpy as np

df=pd.read_csv("datasets/census.csv")

df=df[df['SUMLEV']==50]

df=df.set_index('STNAME').groupby(level=0)['CENSUS2010POP'].agg(np.average)

df.head()

STNAME
Alabama        71339.343284
Alaska         24490.724138
Arizona       426134.466667
Arkansas       38878.906667
California    642309.586207
Name: CENSUS2010POP, dtype: float64

In [32]:
pd.cut(df, 5)

STNAME
Alabama                  (11706.087, 138330.766]
Alaska                   (11706.087, 138330.766]
Arizona                 (390320.176, 516314.881]
Arkansas                 (11706.087, 138330.766]
California              (516314.881, 642309.586]
Colorado                 (11706.087, 138330.766]
Connecticut             (390320.176, 516314.881]
Delaware                (264325.471, 390320.176]
District of Columbia    (516314.881, 642309.586]
Florida                 (264325.471, 390320.176]
Georgia                  (11706.087, 138330.766]
Hawaii                  (264325.471, 390320.176]
Idaho                    (11706.087, 138330.766]
Illinois                 (11706.087, 138330.766]
Indiana                  (11706.087, 138330.766]
Iowa                     (11706.087, 138330.766]
Kansas                   (11706.087, 138330.766]
Kentucky                 (11706.087, 138330.766]
Louisiana                (11706.087, 138330.766]
Maine                    (11706.087, 138330.766]
Maryland                (138330.766, 264325.471]
Massachusetts           (390320.176, 516314.881]
Michigan                 (11706.087, 138330.766]
Minnesota                (11706.087, 138330.766]
Mississippi              (11706.087, 138330.766]
Missouri                 (11706.087, 138330.766]
Montana                  (11706.087, 138330.766]
Nebraska                 (11706.087, 138330.766]
Nevada                  (138330.766, 264325.471]
New Hampshire            (11706.087, 138330.766]
New Jersey              (390320.176, 516314.881]
New Mexico               (11706.087, 138330.766]
New York                (264325.471, 390320.176]
North Carolina           (11706.087, 138330.766]
North Dakota             (11706.087, 138330.766]
Ohio                     (11706.087, 138330.766]
Oklahoma                 (11706.087, 138330.766]
Oregon                   (11706.087, 138330.766]
Pennsylvania            (138330.766, 264325.471]
Rhode Island            (138330.766, 264325.471]
South Carolina           (11706.087, 138330.766]
South Dakota             (11706.087, 138330.766]
Tennessee                (11706.087, 138330.766]
Texas                    (11706.087, 138330.766]
Utah                     (11706.087, 138330.766]
Vermont                  (11706.087, 138330.766]
Virginia                 (11706.087, 138330.766]
Washington              (138330.766, 264325.471]
West Virginia            (11706.087, 138330.766]
Wisconsin                (11706.087, 138330.766]
Wyoming                  (11706.087, 138330.766]
Name: CENSUS2010POP, dtype: category
Categories (5, interval[float64]): [(11706.087, 138330.766] < (138330.766, 264325.471] < (264325.471, 390320.176] < (390320.176, 516314.881] < (516314.881, 642309.586]]

可以看到，全部的数据分割成五部分。每个部分都有对应的区间

In [41]:
S = pd.cut(df, 10)
group_df = pd.DataFrame(data = S).

In [53]:
group_df.reset_index(inplace=True)

In [54]:
group_df.set_index('CENSUS2010POP')

                          index                STNAME
CENSUS2010POP
(11706.087, 75333.413]        0               Alabama
(11706.087, 75333.413]        1                Alaska
(390320.176, 453317.529]      2               Arizona
(11706.087, 75333.413]        3              Arkansas
(579312.234, 642309.586]      4            California
(75333.413, 138330.766]       5              Colorado
(390320.176, 453317.529]      6           Connecticut
(264325.471, 327322.823]      7              Delaware
(579312.234, 642309.586]      8  District of Columbia
(264325.471, 327322.823]      9               Florida
(11706.087, 75333.413]       10               Georgia
(264325.471, 327322.823]     11                Hawaii
(11706.087, 75333.413]       12                 Idaho
(75333.413, 138330.766]      13              Illinois
(11706.087, 75333.413]       14               Indiana
(11706.087, 75333.413]       15                  Iowa
(11706.087, 75333.413]       16                Kansas
(11706.087, 75333.413]       17              Kentucky
(11706.087, 75333.413]       18             Louisiana
(75333.413, 138330.766]      19                 Maine
(201328.118, 264325.471]     20              Maryland
(453317.529, 516314.881]     21         Massachusetts
(75333.413, 138330.766]      22              Michigan
(11706.087, 75333.413]       23             Minnesota
(11706.087, 75333.413]       24           Mississippi
(11706.087, 75333.413]       25              Missouri
(11706.087, 75333.413]       26               Montana
(11706.087, 75333.413]       27              Nebraska
(138330.766, 201328.118]     28                Nevada
(75333.413, 138330.766]      29         New Hampshire
(390320.176, 453317.529]     30            New Jersey
(11706.087, 75333.413]       31            New Mexico
(264325.471, 327322.823]     32              New York
(75333.413, 138330.766]      33        North Carolina
(11706.087, 75333.413]       34          North Dakota
(75333.413, 138330.766]      35                  Ohio
(11706.087, 75333.413]       36              Oklahoma
(75333.413, 138330.766]      37                Oregon
(138330.766, 201328.118]     38          Pennsylvania
(201328.118, 264325.471]     39          Rhode Island
(75333.413, 138330.766]      40        South Carolina
(11706.087, 75333.413]       41          South Dakota
(11706.087, 75333.413]       42             Tennessee
(75333.413, 138330.766]      43                 Texas
(75333.413, 138330.766]      44                  Utah
(11706.087, 75333.413]       45               Vermont
(11706.087, 75333.413]       46              Virginia
(138330.766, 201328.118]     47            Washington
(11706.087, 75333.413]       48         West Virginia
(75333.413, 138330.766]      49             Wisconsin
(11706.087, 75333.413]       50               Wyoming

In [55]:
group_df.drop('index',axis=1, inplace=True)

In [56]:
group_df.head()

       STNAME             CENSUS2010POP
0     Alabama    (11706.087, 75333.413]
1      Alaska    (11706.087, 75333.413]
2     Arizona  (390320.176, 453317.529]
3    Arkansas    (11706.087, 75333.413]
4  California  (579312.234, 642309.586]

In [57]:
group_df.columns

Index(['STNAME', 'CENSUS2010POP'], dtype='object')

In [58]:
group_df.set_index(group_df.columns[1], inplace=True)

In [59]:
group_df.head()

                              STNAME
CENSUS2010POP
(11706.087, 75333.413]       Alabama
(11706.087, 75333.413]        Alaska
(390320.176, 453317.529]     Arizona
(11706.087, 75333.413]      Arkansas
(579312.234, 642309.586]  California

In [61]:
for group, states in group_df.groupby(level=0):
    
    print(f'{group}: {len(states)}')

(11706.087, 75333.413]: 24
(75333.413, 138330.766]: 12
(138330.766, 201328.118]: 3
(201328.118, 264325.471]: 2
(264325.471, 327322.823]: 4
(327322.823, 390320.176]: 0
(390320.176, 453317.529]: 3
(453317.529, 516314.881]: 1
(516314.881, 579312.234]: 0
(579312.234, 642309.586]: 2

In [65]:
group_df.index = group_df.index.astype('object')

In [87]:
pattern = '(?<=\()(?P<lower_number>[\d.]*)(?:,\ )(?P<higher_number>[\d.]*)(?=\])'
nums = group_df[group_df.columns[0]].str.extract(pattern)

In [88]:
nums.head()

                         lower_number higher_number
CENSUS2010POP
(11706.087, 75333.413]            NaN           NaN
(11706.087, 75333.413]            NaN           NaN
(390320.176, 453317.529]          NaN           NaN
(11706.087, 75333.413]            NaN           NaN
(579312.234, 642309.586]          NaN           NaN

In [82]:
group_df.dtypes

STNAME    object
dtype: object

In [86]:
string = '(11706.087, 75333.413]'
import re
pattern = '(?<=\()(?P<lower_number>[\d.]*)(?:,\ )(?P<higher_number>[\d.]*)(?=\])'
re.findall(pattern, string)

[('11706.087', '75333.413')]